package org.octopusden.octopus.jira.config

enum class CacheId {
    ALL_COMPONENTS,
    COMPONENT,
    ALL_JIRA_COMPONENT_VERSION_RANGES,
    JIRA_COMPONENT_VERSION_RANGES_BY_PROJECT_KEY,

    IS_VERSION_MINOR,
    MINOR_VERSION_BY_VERSION,
    MINOR_VERSION_BY_VERSION_NAME_AND_PROJECT,

    JIRA_COMPONENT_BY_PROJECT_VERSION,
    JIRA_COMPONENT_BY_COMPONENT_VERSION,
    JIRA_COMPONENTS_BY_PROJECT_KEY,

    DISTRIBUTION_BY_JIRA_PROJECT_VERSION,
    DISTRIBUTION_BY_PROJECT_KEY,
    DISTRIBUTION_BY_COMPONENT_VERSION,

    VCS_SETTINGS_BY_JIRA_PROJECT_VERSION,
    VCS_SETTINGS_BY_COMPONENT_VERSION,

    EXTERNAL_REGISTRY_VCS_SETTINGS,

    IS_COMPONENT_EXISTS_BY_PROJECT_VERSION,
    IS_COMPONENT_EXISTS_BY_PROJECT_KEY,

    DETAILED_COMPONENT_VERSION,
    DETAILED_COMPONENT_VERSIONS;

    fun id(): String {
        return "ComponentRegistryService:$name"
    }
}
